import type { ModelItem } from '../../../types/studio';

export const FALLBACK_MODELS: ModelItem[] = [
  {
    model_id: 'mms-tts-lug',
    name: 'Sherpa-ONNX MMS-TTS Luganda',
    family: 'VITS / MMS',
    task: 'Text-to-Speech',
    languages: ['lug'],
    size_mb: 35,
    ram_mb: 45,
    is_downloaded: true,
    local_path: '~/.cache/lingualdub/models/mms-tts-lug.onnx',
    description: 'Ultra-low latency offline Luganda neural TTS. Runs on edge CPUs with INT8 quantization.',
  },
  {
    model_id: 'mms-tts-swa',
    name: 'Sherpa-ONNX MMS-TTS Swahili',
    family: 'VITS / MMS',
    task: 'Text-to-Speech',
    languages: ['swa'],
    size_mb: 38,
    ram_mb: 45,
    is_downloaded: true,
    local_path: '~/.cache/lingualdub/models/mms-tts-swa.onnx',
    description: 'Native East African Swahili prosody engine for offline IVR and public address systems.',
  },
  {
    model_id: 'omnivoice-q4',
    name: 'OmniVoice Voice Cloner (GGUF)',
    family: 'OmniVoice',
    task: 'Voice Cloning',
    languages: ['lug', 'swa', 'yor', 'ibo', 'zul', 'amh'],
    size_mb: 380,
    ram_mb: 512,
    is_downloaded: false,
    local_path: null,
    description: 'Zero-shot acoustic timbre transfer with 192-d ECAPA embeddings. Q4_K_M quantization.',
  },
  {
    model_id: 'nllb-200-distilled',
    name: 'NLLB-200 600M Distilled (CTranslate2)',
    family: 'NLLB',
    task: 'Translation',
    languages: ['lug', 'nyn', 'ach', 'swa', 'yor', 'ibo', 'hau', 'zul', 'amh', 'eng', 'fra'],
    size_mb: 640,
    ram_mb: 800,
    is_downloaded: false,
    local_path: null,
    description: 'Many-to-many African neural machine translation engine optimized with 8-bit weights.',
  },
  {
    model_id: 'whisper-small-afri',
    name: 'Whisper Small African Fine-Tuned',
    family: 'Whisper',
    task: 'Speech Recognition',
    languages: ['swa', 'yor', 'hau', 'zul', 'amh', 'lug'],
    size_mb: 460,
    ram_mb: 600,
    is_downloaded: false,
    local_path: null,
    description: 'Robust automatic speech recognition tuned for accented African English and regional idioms.',
  },
];
